import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  UserButton,
  SignInButton,
  SignUpButton,
  SignedOut,
  SignedIn,
} from "@clerk/nextjs";
import { Home, List } from "lucide-react"
import Link from "next/link";
import { currentUser } from "@clerk/nextjs/server";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Navbar />
          <div className="max-w-2xl mx-auto p-8">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}

const Navbar = async () => {
  const user = await currentUser();
  const title = user ? `${user.firstName}'s Todos` : "Todos"
  return (
    <header className="flex w-full items-center p-4 gap-4 h-16 border-b">
      <Link href="/">
        <Button variant="secondary">
          <Home/>
        </Button>
      </Link>
      <div className="flex w-full justify-center text-2xl font-extrabold">
        {title}
      </div>
      <div className="flex justify-end items-center">
        <SignedOut>
          <div className="flex gap-4">
            <SignInButton><Button>Sign In</Button></SignInButton>
            <SignUpButton><Button variant="outline">Sign Up</Button></SignUpButton>
          </div>
        </SignedOut>
        <SignedIn>
          <UserButton />
        </SignedIn>
      </div>
    </header>
  );
};